# Generated by Django 3.2.14 on 2023-04-13 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('place', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('district', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('rentpermomth', models.FloatField()),
                ('description', models.CharField(max_length=1000)),
                ('image', models.FileField(upload_to='Property_image')),
                ('status', models.CharField(max_length=255, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
