# Generated by Django 3.2.14 on 2023-04-13 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('landdeals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDetailsLeaser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('place', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('pro_pic', models.FileField(upload_to='leaser_pro_pic')),
                ('idproof', models.FileField(upload_to='lease_id_proof')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RentelApprovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('landloard', models.IntegerField()),
                ('leaser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landdeals.personaldetailsleaser')),
                ('properties', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landdeals.properties')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalDetailsLandloard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('place', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('pro_pic', models.FileField(upload_to='landloard_pro_pic')),
                ('idproof', models.FileField(upload_to='landloard_id_proof')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contarct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaser_name', models.CharField(max_length=255)),
                ('landloard_name', models.CharField(max_length=255)),
                ('rent', models.FloatField()),
                ('leaser', models.IntegerField()),
                ('landloard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('properties', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landdeals.properties')),
            ],
        ),
    ]
