# Generated by Django 3.2.14 on 2023-04-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landdeals', '0003_contract_block1_contract_block2'),
    ]

    operations = [
        migrations.AddField(
            model_name='contarct',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
