# Generated by Django 3.2.14 on 2023-04-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landdeals', '0004_contarct_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contarct',
            name='contract_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contarct',
            name='rent_status',
            field=models.BooleanField(default=True),
        ),
    ]
